services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

  blazor:
    image: blazor
    build:
      context: .
      dockerfile: Blazor/Dockerfile

  blazor-1:
    image: blazor-1
    build:
      context: .
      dockerfile: Blazor/Dockerfile

